### ISSUE TITLE
Falta foto y descripción

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-meliloza#1]
¡Hola, @meliloza !
Falta la foto y la descripción. ¿Tuviste algún problema para subirlas?

¡Saludos!

**Comment by meliloza** [comment]
perdón profe, me colgué con esa parte no la había leído nose porque, ya la subí

**Comment by asanzo** [comment]
Genial Melina!! Fotaza, qué ganas de ir a caminar al verde. La cursada va a estar buena!!
